### ISSUE TITLE
Passing PR for action

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [dependabot/fetch-metadata#298]
Instead of using `on: pull_request_target` we would like to run as a cron:
```
on:
  schedule:
  - cron: '*/30 4-7 * * 1-4'
```

So it only merges during dawn and doesn't get in the way of our devs.

Does this configuration work?
If not would it be possible to change the action to have the pull request number (or url)?

**Comment by jeffwidman** [comment]
👋 sorry for the slow reply.

This action only fetches metadata, it does _not_ do the automerging itself. The automerge examples on the readme are demonstrating how to write your own GitHub Actions workflow file that leverages the metadata _provided_ by this action in order to decide whether to take additional steps... such as automerging.

So when you write your workflow file, then you decide how you wish to run it--cron, whatever.

**Comment by soumyamahunt** [comment]
@jeffwidman for the `cron` event example mentioned, how can we get dependabot metadata from pull request data(i.e. number, url)?
