### ISSUE TITLE
Add support for dependabot-script/custom commit users

### ISSUE THREAD

**Issue by yeikel** [dependabot/fetch-metadata#317]
I am currently running [dependabot-script](https://github.com/dependabot/dependabot-script) in a private GHE instance to generate pull requests for my projects

I would like to leverage this project but this check :  https://github.com/dependabot/fetch-metadata/blob/29dc6db06eafcbc87b2ecc3b760911cc60b43423/src/dependabot/verified_commits.ts#L22-L44 

Expects the sender of the PR to be 'dependabot[bot]' when that's not possible within my context

Would you be open to adding an optional configuration parameter to the action to allow customizing this value?

As a side note, most Action examples suggest this as an optimization : 

>  if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}

 I am willing to send a PR with the same

**Comment by jeffwidman** [comment]
Yes, that makes sense to make it configurable. Happy to accept a PR.

I don't understand the "optimization" suggestion, but a quick PR might make that easier to understand too? Feel free to send two PR's if they're not tied together...

**Comment by jeffwidman** [comment]
Ah makes sense, sounds good to me!

**Comment by jeffwidman** [comment]
Based on the discussion in #332 , what do you think about the idea of instead creating an option that simply enables/disables the internal code check?

That way advanced users can effectively say "I know what I'm doing, turn this off" and then control everything via their GitHub workflow conditions?

I just think that might be less constrictive to advanced users like yourself.

If you agree, rather than amending #331, why don't you create an _alternative_ PR, that way if someone points out something I'm overlooking that means we still need to specify a custom user, we haven't lost that code...

**Comment by yeikel** [comment]
> Based on the discussion in #332 , what do you think about the idea of instead creating an option that simply enables/disables the internal code check?
> 
> That way advanced users can effectively say "I know what I'm doing, turn this off" and then control everything via their GitHub workflow conditions?
> 
> I just think that might be less constrictive to advanced users like yourself.
> 
> If you agree, rather than amending #331, why don't you create an _alternative_ PR, that way if someone points out something I'm overlooking that means we still need to specify a custom user, we haven't lost that code...

That's fair. I'll work on that next

**Comment by jeffwidman** [comment]
Fixed by #336
